{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 6, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "file C:\\Users\\kumar ojja\\Desktop\\HCM_cls\\test_Masterr.py, line 42\n      def test_navigate_to_page(self, page_title):\nE       fixture 'page_title' not found\n>       available fixtures: _xunit_setup_method_fixture_TestDefaultSuite, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, devpi_function_index, devpi_server, devpiserver_makepypistage, doctest_namespace, extra, firefox, httpd_server, include_metadata_in_junit_xml, jenkins_server, jenkins_server_module, metadata, mongo_server, mongo_server_cls, mongo_server_module, mongo_server_sess, monkeypatch, notifications, postgres_server_sess, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, redis_server, redis_server_sess, rethink_empty_db, rethink_make_tables, rethink_module_db, rethink_server, rethink_server_sess, rethink_unique_db, s3_bucket, s3_server, selenium, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, workspace, xvfb_server, xvfb_server_sess\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\kumar ojja\\Desktop\\HCM_cls\\test_Masterr.py:42\n", "test_name": "test_navigate_to_page", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_login", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_branchmaster", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_cadreemaster", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_calendermaster", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_institutemaster", "rerun": "0"}, "6": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_usermanagement", "rerun": "0"}}, "suite_name": "test_Masterr.py"}}}, "date": "May 29, 2023", "start_time": 1685374644.4390943, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "6", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "7"}