{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 6, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "   selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n     (Session info: chrome=113.0.5672.127)\n   Stacktrace:\n   Backtrace:\n   \tGetHandleVerifier [0x003C8893+48451]\n   \t(No symbol) [0x0035B8A1]\n   \t(No symbol) [0x00265058]\n   \t(No symbol) [0x00261843]\n   \t(No symbol) [0x00258AC5]\n   \t(No symbol) [0x00259B2A]\n   \t(No symbol) [0x00258E23]\n   \t(No symbol) [0x00258175]\n   \t(No symbol) [0x0025810C]\n   \t(No symbol) [0x00256D46]\n   \t(No symbol) [0x002574A8]\n   \t(No symbol) [0x002667F2]\n   \t(No symbol) [0x002BCA61]\n   \t(No symbol) [0x002AA2BC]\n   \t(No symbol) [0x002BC482]\n   \t(No symbol) [0x002AA0B6]\n   \t(No symbol) [0x00287E08]\n   \t(No symbol) [0x00288F2D]\n   \tGetHandleVerifier [0x00628E3A+2540266]\n   \tGetHandleVerifier [0x00668959+2801161]\n   \tGetHandleVerifier [0x0066295C+2776588]\n   \tGetHandleVerifier [0x00452280+612144]\n   \t(No symbol) [0x00364F6C]\n   \t(No symbol) [0x003611D8]\n   \t(No symbol) [0x003612BB]\n   \t(No symbol) [0x00354857]\n   \tBaseThreadInitThunk [0x762A7D59+25]\n   \tRtlInitializeExceptionChain [0x773DB74B+107]\n   \tRtlClearBits [0x773DB6CF+191]\n", "test_name": "test_login", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_branchmaster", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_cadreemaster", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_calendermaster", "rerun": "0"}, "4": {"status": "FAIL", "message": "           ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n           urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "test_name": "test_institutemaster", "rerun": "0"}, "5": {"status": "FAIL", "message": "   selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_TIMED_OUT\n     (Session info: chrome=113.0.5672.127)\n   Stacktrace:\n   Backtrace:\n   \tGetHandleVerifier [0x003C8893+48451]\n   \t(No symbol) [0x0035B8A1]\n   \t(No symbol) [0x00265058]\n   \t(No symbol) [0x00261843]\n   \t(No symbol) [0x00258AC5]\n   \t(No symbol) [0x00259B2A]\n   \t(No symbol) [0x00258E23]\n   \t(No symbol) [0x00258175]\n   \t(No symbol) [0x0025810C]\n   \t(No symbol) [0x00256D46]\n   \t(No symbol) [0x002574A8]\n   \t(No symbol) [0x002667F2]\n   \t(No symbol) [0x002BCA61]\n   \t(No symbol) [0x002AA2BC]\n   \t(No symbol) [0x002BC482]\n   \t(No symbol) [0x002AA0B6]\n   \t(No symbol) [0x00287E08]\n   \t(No symbol) [0x00288F2D]\n   \tGetHandleVerifier [0x00628E3A+2540266]\n   \tGetHandleVerifier [0x00668959+2801161]\n   \tGetHandleVerifier [0x0066295C+2776588]\n   \tGetHandleVerifier [0x00452280+612144]\n   \t(No symbol) [0x00364F6C]\n   \t(No symbol) [0x003611D8]\n   \t(No symbol) [0x003612BB]\n   \t(No symbol) [0x00354857]\n   \tBaseThreadInitThunk [0x762A7D59+25]\n   \tRtlInitializeExceptionChain [0x773DB74B+107]\n   \tRtlClearBits [0x773DB6CF+191]\n", "test_name": "test_usermanagement", "rerun": "0"}}, "suite_name": "test_Masterr.py"}}}, "date": "May 29, 2023", "start_time": 1685374890.2762513, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "6", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "6"}